### ISSUE TITLE
Unable to Create a Account

### ISSUE THREAD

**Issue by Alken123** [AlexGarrixen/vimox-frontend#139]
**Its giving me** 

'POST https://localhost:5001/auth/signup net::ERR_SSL_PROTOCOL_ERROR
dispatchXhrRequest @ xhr.js?b50d:177
xhrAdapter @ xhr.js?b50d:13
dispatchRequest @ dispatchRequest.js?5270:52
Promise.then (async)
request @ Axios.js?0a06:61
wrap @ bind.js?1d2b:9
request @ request.ts?82a9:18
signup @ auth.ts?06b8:13
_callee$ @ useFormSignup.ts?8577:20
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
onSubmit @ useFormSignup.ts?8577:18
eval @ formik.esm.js?2983:944
eval @ formik.esm.js?2983:1258
eval @ formik.esm.js?2983:860
Promise.then (async)
eval @ formik.esm.js?2983:836
eval @ formik.esm.js?2983:1258
eval @ formik.esm.js?2983:924
eval @ formik.esm.js?2983:1258
callCallback @ react-dom.development.js?61bb:3945
invokeGuardedCallbackDev @ react-dom.development.js?61bb:3994
invokeGuardedCallback @ react-dom.development.js?61bb:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?61bb:4070
executeDispatch @ react-dom.development.js?61bb:8243
processDispatchQueueItemsInOrder @ react-dom.development.js?61bb:8275
processDispatchQueue @ react-dom.development.js?61bb:8288
dispatchEventsForPlugins @ react-dom.development.js?61bb:8299
eval @ react-dom.development.js?61bb:8508
batchedEventUpdates$1 @ react-dom.development.js?61bb:22396
batchedEventUpdates @ react-dom.development.js?61bb:3745
dispatchEventForPluginEventSystem @ react-dom.development.js?61bb:8507
attemptToDispatchEvent @ react-dom.development.js?61bb:6005
dispatchEvent @ react-dom.development.js?61bb:5924
unstable_runWithPriority @ scheduler.development.js?3069:646
runWithPriority$1 @ react-dom.development.js?61bb:11276
discreteUpdates$1 @ react-dom.development.js?61bb:22413
discreteUpdates @ react-dom.development.js?61bb:3756
dispatchDiscreteEvent @ react-dom.development.js?61bb:5889' 

**error when trying to create an account i added all the necessary variable in the env but couldn’t understand what to add in 'SECRET_REFRESH_JWT','SENDGRID_CLIENT','ORIGIN_CLIENTS'**

**Comment by AlexGarrixen** [comment]
**SENDGRID_CLIENT**:
It is the path of the frontend application
Example: `http://localhost:3000`
 
**SECRET_REFRESH_JWT** :
Secret key to sign the refresh token

**ORIGIN_CLIENTS** :
They are clients who are not blocked by cors. If you are implementing more than one, separate them with the ~ operator, I did it like this to divide and create an array.
Example: `https://localhost:3000~https://localhost:8080` or `https://localhost:3000`

**Comment by Alken123** [comment]
[Image Link](https://i.imgur.com/QydBkDh.png) Its throwing this error any solution ?

**Comment by AlexGarrixen** [comment]
check the server and verify that the environment variables do not have an undefined value.

You can do a console.log in `src/utils/.env.ts` in server and see what happens
