### ISSUE TITLE
Not showing on google search

### ISSUE THREAD

**Issue by rafadsm** [AlexGarrixen/vimox-frontend#142]
Hi, thanks for making this amazing project
I've been running this site for 3 months, but it never appeared on google searches, I even included the meta tags, but I never got a result, I tried it with a simple page and it worked, except with vimox.

**Comment by AlexGarrixen** [comment]
Even being indexed in google?
I will have to review

**Comment by rafadsm** [comment]
yes, but I only find it in searches when using search tools such as `site:xxx` or `inurl:xxx`
